apiVersion: v1
kind: Pod
metadata:
  name: control-center
  labels:
    app: control-center
spec:
  containers:
  - name: control-center
    image: confluentinc/cp-enterprise-control-center:5.3.0
    ports:
    - containerPort: 9021
    env:
    - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
      value: kafka-svc:9092
    - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
      value: zookeeper-svc:2181
    - name: CONTROL_CENTER_REPLICATION_FACTOR
      value: '1'
    - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION
      value: '1'
    - name: CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION
      value: '1'
    - name: CONTROL_CENTER_COMMAND_TOPIC_REPLICATION
      value: '1'
    - name: CONTROL_CENTER_METRICS_TOPIC_REPLICATION
      value: '1'
    - name: CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS
      value: '1'
    - name: CONTROL_CENTER_STREAMS_CONSUMER_REQUEST_TIMEOUT_MS
      value: "960032"
    - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
      value: http://schema-svc:8081
    - name: CONTROL_CENTER_KSQL_URL
      value: http://ksql-server:8088
    - name: CONTROL_CENTER_KSQL_ADVERTISED_URL
      value: http://localhost:8088