apiVersion: v1
kind: Pod
metadata:
  name: ksql-server
  labels:
    app: ksql-server
spec:
  containers:
  - name: ksql-server
    image: confluentinc/cp-ksql-server:5.3.0
    ports:
    - containerPort: 8088
    env:
    - name: KSQL_CONFIG_DIR
      value: /etc/ksql
    - name: KSQL_BOOTSTRAP_SERVERS
      value: kafka-svc:9092
    - name: KSQL_HOST_NAME
      value: ksql-server
    - name: KSQL_APPLICATION_ID
      value: using-ksql
    - name: KSQL_LISTENERS
      value: http://0.0.0.0:8088
    - name: KSQL_CACHE_MAX_BYTES_BUFFERING
      value: '0'
    - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
      value: http://schema-svc:8081
    - name: KSQL_PRODUCER_INTERCEPTOR_CLASSES
      value: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
    - name: KSQL_CONSUMER_INTERCEPTOR_CLASSES
      value: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
    - name: KSQL_KSQL_SERVER_UI_ENABLED
      value: 'false'