apiVersion: v1
kind: Pod
metadata:
  name: consumer
spec:
  containers:
  - name: consumer
    image: hleeanex/sample-consumer:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
