apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      name: consumer
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: hleeanex/sample-consumer:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
