apiVersion: v1
kind: Pod
metadata:
  name: schema-pod
  labels:
    app: schema-registry
spec:
  containers:
    - name: schema-registry
      image: confluentinc/cp-schema-registry:5.3.0
      ports:
      - containerPort: 8081
      env:
      - name: SCHEMA_REGISTRY_HOST_NAME
        value: schema-svc
      - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
        value: zookeeper-svc:2181
      - name: SCHEMA_REGISTRY_LISTENERS
        value: http://0.0.0.0:8081

